namespace MyBantu.Application.Abstractions;

/// <summary>
/// Local original-document storage. Filenames are always generated by the
/// application; user-supplied names are never used as paths.
/// </summary>
public interface IDocumentFileStore
{
    /// <summary>Saves the stream under the generated name and returns (absolutePath, sha256, sizeBytes).</summary>
    Task<StoredFile> SaveAsync(string storedFileName, Stream content, CancellationToken cancellationToken);

    /// <summary>Absolute path of a stored file (for the internal Document AI call).</summary>
    string GetAbsolutePath(string storedFileName);

    /// <summary>Deletes the stored file. Idempotent.</summary>
    void Delete(string storedFileName);
}

public sealed record StoredFile(string AbsolutePath, string Sha256, long SizeBytes);
